### ISSUE TITLE
Water Main Break

### ISSUE THREAD

**Issue by camrynallen** [nmfs-openscapes/2022-noaa-swfsc-pifsc-fall#11]
**Is your feature request related to a problem? Please describe.**

- [x] @camrynallen  hose duty
- [x] @kmyano  watering without water

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kmyano** [comment]
What's going on

**Comment by camrynallen** [comment]
I accomplished my task

**Comment by acossio** [comment]
Good luck with the water main break
