### ISSUE TITLE
We have an issue

### ISSUE THREAD

**Issue by ybarkley** [nmfs-openscapes/2022-noaa-swfsc-pifsc-fall#13]
**Is your feature request related to a problem? Please describe.**
Something is wonky when running that thing.

**Describe the solution you'd like**
The correct answer to all the questions.

**Describe alternatives you've considered**
None.

**Additional context**
NA

**Comment by ybarkley** [comment]
Here's my request! DO IT....

**Comment by shannonrankin** [comment]
Yes ma'am, getting right on it.
