### ISSUE TITLE
Cameron's test issue

### ISSUE THREAD

**Issue by cameronspeir** [nmfs-openscapes/2022-noaa-swfsc-pifsc-fall#18]
Check out this issue  @sfregosi @sroden76 

- [x] Task 1
- [x] Task 2

Please check the boxes by **Friday**

**Comment by sfregosi** [comment]
Thanks! I'll start on Task 1 now.

**Comment by sroden76** [comment]
I'll look at task 2

**Comment by cameronspeir** [comment]
Thanks, all.
