### ISSUE TITLE
Need help from breakout room 2

### ISSUE THREAD

**Issue by amandalbradford** [nmfs-openscapes/2022-noaa-swfsc-pifsc-fall#6]
Aloha @jsuca18 and @tanyalrogers - 

I could really use your help with the following items:
- [x] update code
- [x] finish paper review
- [x] work on next project

**Thanks so much!**
amanda

**Comment by jsuca18** [comment]
Updated the imaginary code!

**Comment by amandalbradford** [comment]
I finished the tasks!
